version: '3.7'

services:

  wordpress:
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: wp.Dockerfile
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dev
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: devdb
    volumes:
      - wordpress:/var/www/html

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: devdb
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
